MVCBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MVCBank.Models;

namespace MVCBank.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCBank/Controllers/TransactionController.cs
using MVCBank.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBank.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transaction
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
                
            }

            return View();
        }
    }
}

MVCBank/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCBank/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCBank/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>Networld Computer Consulting Group</h1>
    <p class="lead">We Offer Various Comptuing Consulting Services Give it a try today! </p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Powered by ASP.NET</a></p>
</div>*@

@*<div class="row">
    <div class="col-md-4">
        <h2>Register</h2>
        <p>
            Open an account with us
        </p>
        <p>@Html.ActionLink("Register","Register", "Account", null, new {@class="btn btn-default"})</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Register</a></p>
    </div>
    <div class="col-md-4">
        <h2>Log in</h2>
        <p>Access your existing account</p>
        <p>@Html.ActionLink("Log in", "Login", "Account", null, new { @class = "btn btn-default" })</p>
    </div>

</div>*@

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-lg btn-block" ><span class="glyphicon glyphicon-circle-arrow-down"  ></span> Withdrawal</a>
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-flash"></span> Quick Cash $100</a>
        <a href="@Url.Action("Details","CheckingAccount")" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry</a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-print"></span> Print Statement</a>
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
        <a href="@Url.Action("Deposit", "Transaction", new {checkingAccountId = ViewBag.CheckingAccountID})" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span> Deposit</a>
    </div>
</div>